name: 🔄 Update Recent GitHub Activity

on:
  schedule:
    - cron: "0 */6 * * *"  # Cada 6 horas
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v3

      - name: 🪄 Update recent GitHub activity
        uses: JamesIves/github-activity-readme@v0.3.0
        with:
          COMMIT_MSG: "🔄 Update recent GitHub activity"
          MAX_LINES: 5
