name: ⏰ Update README Date

on:
  schedule:
    - cron: "0 5 * * *" # Todos los días a las 5 AM UTC
  workflow_dispatch:

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update date in README
        run: |
          DATE=$(date +"%B %d, %Y")
          sed -i "s/{{ DATE_AUTO }}/$DATE/" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "🕒 Update README date to $DATE" || exit 0
          git push
